version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - kafkaenqueue_default
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    networks:
      - kafkaenqueue_default
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_0_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  kafka-ui:
    image: provectuslabs/kafka-ui
    networks:
      - kafkaenqueue_default
    container_name: kafka-ui-2
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      - KAFKA_CLUSTERS_0_READONLY=false

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./:/app
    links:
      - php-fpm
    ports:
      - "80:80"
    networks:
      - kafkaenqueue_default
  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./:/app
    ports:
      - "9000:9000"
    networks:
      - kafkaenqueue_default

networks:
  kafkaenqueue_default:
    driver: bridge


